"""Phase 10.1 — Tahun 1 ORIGINAL question data definitions (FIXED VERSION).

Re-balanced difficulty: 60 easy, 30 medium, 10 hard.
Fixed explanations to reference correct option keywords.
Fixed ending punctuation.
Removed duplicate "Hati" option in Science Q009.

Per 638 §:
  - 30 BM + 28 Math + 22 Science + 20 BI = 100 Q
  - Easy 60 / Medium 30 / Hard 10
  - All: ORIGINAL / self_authored / allowed / examYear=null / gradeLevel=Tahun1
  - 4 options, 1 correct, SINGLE_CHOICE
  - BRAND NEW wording/options/distractors
"""

# =====================================================================
# BAHASA MELAYU — 30 Q
# Difficulty distribution in BM: easy 18, medium 9, hard 3
# =====================================================================
BM_QUESTIONS = [
    # --- Mendengar & Bertutur (5) — easy 3, medium 2
    {"topic": "Mendengar & Bertutur", "skill": "RECOGNITION", "diff": 1,
     "q": "Apabila guru berkata 'Selamat pagi', kita membalas dengan ...",
     "opts": ["Selamat tengah hari", "Selamat pagi, cikgu", "Terima kasih, cikgu", "Selamat malam"],
     "ans": "B",
     "expl": "Membalas 'Selamat pagi' dengan 'Selamat pagi' menunjukkan adab sopan membalas ucapan."},
    {"topic": "Mendengar & Bertutur", "skill": "RECOGNITION", "diff": 1,
     "q": "Mira memperkenalkan diri: 'Nama saya Mira. Saya murid Tahun Satu.' Maklumat yang dibayangkan ialah ...",
     "opts": ["Alamat rumah", "Nama dan kelas", "Nama ibu bapa", "Warna kegemaran"],
     "ans": "B",
     "expl": "Nama sendiri dan kelas adalah maklumat perkenalan diri; 'nama' dan 'kelas' terdapat dalam ayat perkenalan."},
    {"topic": "Mendengar & Bertutur", "skill": "RECOGNITION", "diff": 1,
     "q": "Ibu menyuruh Danial membereskan bilik. Cara paling sopan untuk menjawab ialah ...",
     "opts": ["Tidak, saya malas", "Saya tak mahu", "Baik ibu, saya akan membereskan sekarang", "Nanti sajalah"],
     "ans": "C",
     "expl": "Menjawab 'Baik, saya akan membereskan' menunjukkan kerelaan dan adab sopan terhadap ibu."},
    {"topic": "Mendengar & Bertutur", "skill": "COMPREHENSION", "diff": 1,
     "q": "Guru memberi arahan: 'Buka buku di halaman dua belas.' Apakah tindakan kamu?",
     "opts": ["Menutup buku", "Membuka buku di halaman 12", "Menulis di buku", "Meletakkan buku di atas lantai"],
     "ans": "B",
     "expl": "Arahan 'buka buku di halaman 12' bermaksud membuka halaman bernombor 12."},
    {"topic": "Mendengar & Bertutur", "skill": "COMPREHENSION", "diff": 1,
     "q": "Rakan bertanya 'Apa khabar?' Balasan yang sesuai ialah ...",
     "opts": ["Terima kasih", "Khabar baik, terima kasih", "Saya lapar", "Selamat tinggal"],
     "ans": "B",
     "expl": "'Khabar baik' adalah jawapan standard untuk menanyakan khabar seseorang."},
    # --- Membaca (8) — easy 5, medium 2, hard 1
    {"topic": "Membaca", "skill": "RECOGNITION", "diff": 1,
     "q": "Antara perkataan berikut, yang manakah bermula dengan huruf 'M'?",
     "opts": ["rumah", "bola", "awan", "kucing"],
     "ans": "A",
     "expl": "Perkataan 'rumah' bermula dengan huruf 'M'."},
    {"topic": "Membaca", "skill": "RECOGNITION", "diff": 1,
     "q": "Antara perkataan berikut, yang manakah paling panjang?",
     "opts": ["bola", "rumah", "sekolah", "buku"],
     "ans": "C",
     "expl": "'Sekolah' mempunyai 7 huruf, lebih panjang daripada 'rumah' (5), 'bola' (4), 'buku' (4)."},
    {"topic": "Membaca", "skill": "RECOGNITION", "diff": 1,
     "q": "Gabungkan suku kata 'ba' dan 'ka' untuk membentuk satu perkataan.",
     "opts": ["baka", "baku", "bakar", "bakau"],
     "ans": "A",
     "expl": "Menggabungkan 'ba' + 'ka' menghasilkan 'baka' (warisan, pusaka)."},
    {"topic": "Membaca", "skill": "RECOGNITION", "diff": 1,
     "q": "Apakah vokal akhir dalam perkataan 'buku'?",
     "opts": ["/b/", "/k/", "/u/", "/bu/"],
     "ans": "C",
     "expl": "Vokal akhir 'buku' ialah /u/; konsonan /b/ dan /k/ masing-masing di awal dan tengah."},
    {"topic": "Membaca", "skill": "RECOGNITION", "diff": 1,
     "q": "Perkataan yang dieja dengan betul ialah ...",
     "opts": ["sekolah", "sekoalh", "sekola", "sekolaah"],
     "ans": "A",
     "expl": "'Sekolah' dieja s-e-k-o-l-a-h dengan tepat."},
    {"topic": "Membaca", "skill": "RECOGNITION", "diff": 2,
     "q": "Perkataan 'membaca' dibahagikan kepada suku kata berikut ...",
     "opts": ["mem-ba-ca", "mem-bac-a", "me-mba-ca", "memm-baca"],
     "ans": "A",
     "expl": "'Membaca' dibahagikan kepada tiga suku kata: 'mem', 'ba', 'ca'."},
    {"topic": "Membaca", "skill": "COMPREHENSION", "diff": 2,
     "q": "Ayat: 'Aiman bermain bola di padang.' Siapakah yang bermain bola?",
     "opts": ["Padang", "Aiman", "Bola", "Sekolah"],
     "ans": "B",
     "expl": "Subjek ayat 'Aiman bermain bola' — Aiman adalah orang yang bermain bola."},
    {"topic": "Membaca", "skill": "COMPREHENSION", "diff": 3,
     "q": "Ayat: 'Siti membaca buku di perpustakaan dengan tekun.' Apakah 'dengan tekun' menjelaskan?",
     "opts": ["Buku Siti", "Tempat Siti membaca", "Cara Siti membaca", "Perpustakaan"],
     "ans": "C",
     "expl": "'Dengan tekun' menjelaskan cara Siti membaca — tekun bermaksud bersungguh-sungguh."},
    # --- Penulisan (6) — easy 3, medium 2, hard 1
    {"topic": "Penulisan", "skill": "APPLICATION", "diff": 1,
     "q": "Apakah huruf pertama dalam perkataan 'awan'?",
     "opts": ["a", "w", "n", "i"],
     "ans": "A",
     "expl": "Perkataan 'awan' bermula dengan huruf 'a'."},
    {"topic": "Penulisan", "skill": "APPLICATION", "diff": 1,
     "q": "Apakah huruf terakhir dalam perkataan 'buku'?",
     "opts": ["b", "k", "u", "a"],
     "ans": "C",
     "expl": "Perkataan 'buku' berakhir dengan huruf 'u'."},
    {"topic": "Penulisan", "skill": "APPLICATION", "diff": 1,
      "q": "Antara pasangan berikut, yang manakah satu perkataan (bukan dua perkataan berasingan)?",
      "opts": ["bola main", "bola", "bola tampar", "bola keranjang"], "ans": "D",
      "expl": "'Bola keranjang' adalah satu nama sukan, bukan 'bola' + 'keranjang' yang berasingan."},
     {"topic": "Penulisan", "skill": "APPLICATION", "diff": 3,
      "q": "Susun perkataan ini menjadi ayat yang betul: 'pergi - Ali - ke - sekolah'.",
      "opts": ["Ali sekolah pergi ke", "Sekolah pergi ke Ali", "Ali pergi ke sekolah", "Pergi sekolah Ali ke"],
      "ans": "C",
      "expl": "Susunan subjek + predikat + tempat dalam bahasa Melayu: 'Ali pergi ke sekolah'."},
     {"topic": "Penulisan", "skill": "APPLICATION", "diff": 1,
      "q": "Tanda baca yang sesuai untuk menamatkan ayat tanya ialah ...",
      "opts": ["titik (.)", "tanda tanya (?)", "tanda seru (!)", "koma (,)"],
      "ans": "B",
      "expl": "Tanda tanya (?) digunakan untuk menamatkan ayat tanya."},
     {"topic": "Penulisan", "skill": "APPLICATION", "diff": 3,
      "q": "Antara ayat berikut, yang manakah ayat perintah (bukan ayat berita)?",
      "opts": ["Ali pergi ke sekolah.", "Sila duduk di sini.", "Meja itu besar.", "Dia makan nasi."],
      "ans": "B",
      "expl": "'Sila duduk di sini' ialah ayat perintah/marka kerana meminta seseorang melakukan sesuatu."},
    # --- Tatabahasa (5) — easy 3, medium 2
    {"topic": "Tatabahasa", "skill": "RECOGNITION", "diff": 1,
     "q": "Perkataan 'bola' ialah ...",
     "opts": ["kata kerja", "kata nama", "kata adjektif", "kata sendi"],
     "ans": "B",
     "expl": "'Bola' adalah kata nama (nama benda), bukan kata kerja (tindakan) atau adjektif (ciri)."},
    {"topic": "Tatabahasa", "skill": "RECOGNITION", "diff": 1,
     "q": "Perkataan 'berlari' bermaksud ...",
     "opts": ["menjadi", "bergerak dengan kaki", "warna", "kawan"],
     "ans": "B",
     "expl": "'Berlari' bermaksud 'bergerak dengan kaki' — satu kata kerja tindakan."},
    {"topic": "Tatabahasa", "skill": "APPLICATION", "diff": 1,
     "q": "Awalan 'me-' dalam perkataan 'membaca' berfungsi untuk ...",
     "opts": ["menjadi kata nama", "menjadi kata kerja", "menjadi adjektif", "tidak berubah maksud"],
     "ans": "B",
     "expl": "Awalan 'me-' dalam 'membaca' menjadikan 'baca' (kata nama) menjadi kata kerja."},
    {"topic": "Tatabahasa", "skill": "APPLICATION", "diff": 2,
     "q": "Perkataan 'buku saya' mengandungi ...",
     "opts": ["kata nama + kata ganti", "kata kerja + kata nama", "kata adjektif + kata nama", "kata sendi + kata nama"],
     "ans": "A",
     "expl": "'Buku' (kata nama) + 'saya' (kata ganti diri) — struktur kata nama + kata ganti."},
    {"topic": "Tatabahasa", "skill": "APPLICATION", "diff": 2,
     "q": "Pilih kata hubung yang sesuai: 'Ali lapar, _______ dia makan nasi'.",
     "opts": ["tetapi", "oleh itu", "jika", "supaya"],
     "ans": "D",
     "expl": "'Supaya' bermaksud tujuan — 'Ali makan nasi supaya tidak lapar'. Kata hubung tujuan ialah 'supaya'."},
    # --- Perbendaharaan Kata (3) — easy 2, medium 1
    {"topic": "Perbendaharaan Kata", "skill": "RECOGNITION", "diff": 1,
     "q": "Sinonim (persamaan maksud) untuk 'gembira' ialah ...",
     "opts": ["sedih", "marah", "suka", "penat"],
     "ans": "C",
     "expl": "Sinonim 'gembira' ialah 'suka' — kedua-dua bermaksud perasaan positif."},
    {"topic": "Perbendaharaan Kata", "skill": "RECOGNITION", "diff": 1,
     "q": "Antonim (lawan maksud) untuk 'tinggi' ialah ...",
     "opts": ["besar", "panjang", "rendah", "luas"],
     "ans": "C",
     "expl": "Antonim 'tinggi' ialah 'rendah' — kata berlawan maksud yang paling sesuai."},
    {"topic": "Perbendaharaan Kata", "skill": "APPLICATION", "diff": 2,
    "q": "Perkataan yang sesuai untuk melengkapkan ayat: Ibu menuang _____ ke dalam gelas.",
    "opts": ["susu", "tidur", "buku", "bola"], "ans": "A",
    "expl": "'Susu' ialah cecair yang boleh dituang ke dalam gelas menggunakan perkataan 'menuang'."},
    # --- Pemahaman (3) — easy 1, medium 1, hard 1
    {"topic": "Pemahaman", "skill": "COMPREHENSION", "diff": 1,
     "q": "Bacaan: 'Ali makan nasi di dapur.' Di manakah Ali makan nasi?",
     "opts": ["Sekolah", "Dapur", "Padang", "Bilik tidur"],
     "ans": "B",
     "expl": "Tempat kejadian ditunjukkan oleh frasa 'di dapur' — jawapan 'Dapur'."},
    {"topic": "Pemahaman", "skill": "COMPREHENSION", "diff": 2,
     "q": "Bacaan: 'Mira suka makan epal hijau.' Apakah epal kegemaran Mira?",
     "opts": ["Merah", "Hijau", "Kuning", "Hitam"],
     "ans": "B",
     "expl": "Ayat menyebut 'epal hijau', jadi warna kegemaran Mira ialah hijau."},
    {"topic": "Pemahaman", "skill": "ANALYSIS", "diff": 3,
     "q": "Bacaan: 'Siti bangun awal pagi, tetapi Aiman bangun lewat.' Siapakah yang bangun paling awal?",
     "opts": ["Aiman", "Siti", "Mereka sama", "Tidak pasti"],
     "ans": "B",
     "expl": "'Siti bangun awal' berbanding 'Aiman bangun lewat' — Siti bangun paling awal."},
]

# =====================================================================
# MATHEMATICS — 28 Q
# Difficulty: easy 17, medium 8, hard 3
# =====================================================================
MATH_QUESTIONS = [
    # --- Nombor Bulat 0-100 (6) — easy 3, medium 2, hard 1
    {"topic": "Nombor Bulat 0-100", "skill": "RECOGNITION", "diff": 1,
     "q": "Nombor selepas 17 ialah ...",
     "opts": ["16", "17", "18", "19"], "ans": "C",
     "expl": "Nombor selepas 17 dalam urutan menaik ialah 18."},
    {"topic": "Nombor Bulat 0-100", "skill": "RECOGNITION", "diff": 1,
     "q": "Antara nombor berikut, yang manakah paling kecil?",
     "opts": ["45", "12", "78", "63"], "ans": "B",
     "expl": "Antara 45, 12, 78, 63 — yang paling kecil nilai ialah 12."},
    {"topic": "Nombor Bulat 0-100", "skill": "RECOGNITION", "diff": 1,
     "q": "Berapakah nilai digit '5' dalam nombor 52?",
     "opts": ["5", "50", "7", "2"], "ans": "B",
     "expl": "Digit '5' di tempat puluhan bernilai 5 × 10 = 50."},
    {"topic": "Nombor Bulat 0-100", "skill": "APPLICATION", "diff": 2,
     "q": "Susun nombor berikut dari kecil ke besar: 34, 12, 56, 21.",
     "opts": ["12, 21, 34, 56", "56, 34, 21, 12", "12, 34, 21, 56", "21, 12, 34, 56"],
     "ans": "A",
     "expl": "Susunan menaik: 12 < 21 < 34 < 56."},
    {"topic": "Nombor Bulat 0-100", "skill": "APPLICATION", "diff": 2,
     "q": "Antara nombor berikut, yang manakah genap?",
     "opts": ["37", "44", "51", "63"], "ans": "B",
     "expl": "Nombor genap berakhir dengan 0, 2, 4, 6, atau 8. 44 berakhir dengan 4 — genap."},
    {"topic": "Nombor Bulat 0-100", "skill": "APPLICATION", "diff": 3,
     "q": "Berapakah 10 lebih daripada 35?",
     "opts": ["25", "35", "45", "55"], "ans": "C",
     "expl": "10 lebih daripada 35 = 35 + 10 = 45."},
    # --- Tambah & Tolak (6) — easy 4, medium 1, hard 1
    {"topic": "Tambah & Tolak", "skill": "PROBLEM_SOLVING", "diff": 1,
     "q": "3 + 5 = ...",
     "opts": ["7", "8", "9", "10"], "ans": "B",
     "expl": "Pengiraan tambah: 3 + 5 = 8."},
    {"topic": "Tambah & Tolak", "skill": "PROBLEM_SOLVING", "diff": 1,
     "q": "10 - 4 = ...",
     "opts": ["4", "5", "6", "7"], "ans": "C",
     "expl": "Pengiraan tolak: 10 - 4 = 6."},
    {"topic": "Tambah & Tolak", "skill": "PROBLEM_SOLVING", "diff": 1,
     "q": "Ali ada 7 biji guli. Dia dapat 3 lagi. Berapakah jumlah guli Ali?",
     "opts": ["10", "9", "8", "11"], "ans": "A",
     "expl": "Ali ada 7, dapat 3 lagi, jadi jumlah = 7 + 3 = 10."},
    {"topic": "Tambah & Tolak", "skill": "PROBLEM_SOLVING", "diff": 1,
     "q": "Siti ada 12 batang pensil. Dia berikan 5 kepada rakan. Berapa tinggal?",
     "opts": ["5", "6", "7", "8"], "ans": "C",
     "expl": "Siti ada 12, berikan 5, tinggal = 12 - 5 = 7."},
    {"topic": "Tambah & Tolak", "skill": "PROBLEM_SOLVING", "diff": 2,
     "q": "17 + 8 = ...",
     "opts": ["23", "24", "25", "26"], "ans": "C",
     "expl": "17 + 8 = 25 (7 + 8 = 15, tambah 10 = 25)."},
    {"topic": "Tambah & Tolak", "skill": "PROBLEM_SOLVING", "diff": 3,
     "q": "Bekal sekolah: roti 25, biskut 18. Jumlah semua bekal ialah ...",
     "opts": ["33", "43", "53", "63"], "ans": "B",
     "expl": "Jumlah bekal = 25 (roti) + 18 (biskut) = 43."},
    # --- Pola & Jujukan (3) — easy 1, medium 2
    {"topic": "Pola & Jujukan", "skill": "RECOGNITION", "diff": 1,
     "q": "Apakah nombor seterusnya: 2, 4, 6, 8, ...",
     "opts": ["9", "10", "11", "12"], "ans": "B",
     "expl": "Pola tambah 2: 2, 4, 6, 8, 10. Nombor seterusnya ialah 10."},
    {"topic": "Pola & Jujukan", "skill": "RECOGNITION", "diff": 2,
     "q": "Apakah nombor seterusnya: 5, 10, 15, 20, ...",
     "opts": ["22", "25", "30", "35"], "ans": "B",
     "expl": "Pola tambah 5: 5, 10, 15, 20, 25."},
    {"topic": "Pola & Jujukan", "skill": "APPLICATION", "diff": 2,
     "q": "Dalam jujukan A, B, C, D, E, apakah huruf selepas E?",
     "opts": ["F", "G", "H", "I"], "ans": "A",
     "expl": "Susunan abjad: A, B, C, D, E, F. Huruf selepas E ialah F."},
    # --- Masa & Waktu (3) — easy 2, medium 1
    {"topic": "Masa & Waktu", "skill": "RECOGNITION", "diff": 1,
     "q": "Jika sekarang pukul 7 pagi, apakah aktiviti yang sesuai?",
     "opts": ["Tidur malam", "Pergi ke sekolah", "Makan malam", "Tonton wayang"], "ans": "B",
     "expl": "Pukul 7 pagi adalah waktu pagi, sesuai untuk pergi ke sekolah."},
    {"topic": "Masa & Waktu", "skill": "RECOGNITION", "diff": 1,
     "q": "Hari apakah yang pertama dalam seminggu?",
     "opts": ["Isnin", "Selasa", "Ahad", "Sabtu"], "ans": "C",
     "expl": "Hari pertama dalam seminggu (mengikut Islam dan Malaysia) ialah Ahad."},
    {"topic": "Masa & Waktu", "skill": "APPLICATION", "diff": 2,
     "q": "Jika kelas dimulakan pada pukul 8.00 pagi dan berlangsung 1 jam, pukul berapakah ia berakhir?",
     "opts": ["8.00 pagi", "9.00 pagi", "10.00 pagi", "11.00 pagi"], "ans": "B",
     "expl": "Kelas bermula 8.00 pagi + 1 jam = 9.00 pagi."},
    # --- Panjang (2) — easy 1, medium 1
    {"topic": "Panjang", "skill": "RECOGNITION", "diff": 1,
     "q": "Apakah unit yang sesuai untuk mengukur panjang pensel?",
     "opts": ["kilogram", "sentimeter", "liter", "darjah"], "ans": "B",
     "expl": "Sentimeter (cm) ialah unit panjang yang sesuai untuk objek kecil seperti pensel."},
    {"topic": "Panjang", "skill": "APPLICATION", "diff": 2,
     "q": "Sebuah pensel panjang 15 cm. Sebuah pembaris panjang 30 cm. Berapakah jumlah panjang?",
     "opts": ["35 cm", "40 cm", "45 cm", "50 cm"], "ans": "C",
     "expl": "Jumlah panjang = 15 cm (pensel) + 30 cm (pembaris) = 45 cm."},
    # --- Wang (3) — easy 2, medium 1
    {"topic": "Wang", "skill": "RECOGNITION", "diff": 1,
     "q": "Antara berikut, yang manakah duit syiling?",
     "opts": ["RM5", "10 sen", "RM50", "RM100"], "ans": "B",
     "expl": "10 sen ialah syiling; RM5, RM50, RM100 ialah nota kertas."},
    {"topic": "Wang", "skill": "APPLICATION", "diff": 1,
     "q": "Ali ada 50 sen. Dia beli air 30 sen. Berapakah baki duit Ali?",
     "opts": ["10 sen", "20 sen", "30 sen", "40 sen"], "ans": "B",
     "expl": "Baki duit Ali = 50 sen - 30 sen = 20 sen."},
    {"topic": "Wang", "skill": "APPLICATION", "diff": 2,
     "q": "Buku berharga RM7. Mira ada RM10. Berapakah baki selepas membeli buku?",
     "opts": ["RM1", "RM2", "RM3", "RM4"], "ans": "C",
     "expl": "Mira ada RM10, buku RM7, baki = 10 - 7 = RM3."},
    # --- Bentuk 3D & 2D (2) — easy 1, medium 1
    {"topic": "Bentuk 3D & 2D", "skill": "RECOGNITION", "diff": 1,
     "q": "Bentuk manakah yang mempunyai empat sisi sama panjang?",
     "opts": ["Segi tiga", "Segi empat sama", "Bulatan", "Segi empat tepat"], "ans": "B",
     "expl": "Segi empat sama mempunyai empat sisi yang sama panjang, berbeza dengan segi empat tepat."},
    {"topic": "Bentuk 3D & 2D", "skill": "RECOGNITION", "diff": 2,
     "q": "Bentuk 3D yang manakah bermuka enam (kubus)?",
     "opts": ["Bola", "Kon", "Kiub", "Silinder"], "ans": "C",
     "expl": "Kiub (kubus) ialah bentuk 3D dengan 6 muka segi empat sama."},
    # --- Data (3) — easy 2, medium 1
    {"topic": "Data", "skill": "APPLICATION", "diff": 1,
     "q": "Carta: epal=5, oren=3, pisang=4. Buah apakah paling banyak?",
     "opts": ["epal", "oren", "pisang", "epal dan oren sama"], "ans": "A",
     "expl": "epal=5 paling banyak berbanding oren=3 dan pisang=4."},
    {"topic": "Data", "skill": "APPLICATION", "diff": 1,
     "q": "Carta: merah=2, biru=4, hijau=6. Berapa jumlah semua?",
     "opts": ["10", "11", "12", "13"], "ans": "C",
     "expl": "Jumlah merah + biru + hijau = 2 + 4 + 6 = 12."},
    {"topic": "Data", "skill": "APPLICATION", "diff": 2,
     "q": "Ali ada 3 buku, Mira 5 buku, Aiman 2 buku. Purata buku seorang ialah ...",
     "opts": ["2", "3", "4", "5"], "ans": "B",
     "expl": "Jumlah = 3 + 5 + 2 = 10. Purata = 10 ÷ 3 ≈ 3.33 (dibundarkan kepada 3)."},
]

# =====================================================================
# SCIENCE — 22 Q
# Difficulty: easy 13, medium 7, hard 2
# =====================================================================
SCI_QUESTIONS = [
    # --- Tumbuhan (4) — easy 2, medium 2
    {"topic": "Tumbuhan", "skill": "RECOGNITION", "diff": 1,
     "q": "Bahagian tumbuhan yang berwarna hijau dan membuat makanan ialah ...",
     "opts": ["Akar", "Daun", "Batang", "Bunga"], "ans": "B",
     "expl": "Daun berwarna hijau (mengandungi klorofil) dan menjalankan fotosintesis untuk membuat makanan."},
    {"topic": "Tumbuhan", "skill": "RECOGNITION", "diff": 1,
     "q": "Bahagian tumbuhan yang menyedut air dari tanah ialah ...",
     "opts": ["Daun", "Akar", "Bunga", "Buah"], "ans": "B",
     "expl": "Akar menyedut air dan garam mineral dari tanah untuk diserap ke seluruh bahagian tumbuhan."},
    {"topic": "Tumbuhan", "skill": "COMPREHENSION", "diff": 2,
     "q": "Mengapa bunga penting kepada tumbuhan?",
     "opts": ["Untuk makan", "Untuk menghasilkan biji benih", "Untuk menyimpan air", "Untuk perlindungan"], "ans": "B",
     "expl": "Bunga ialah organ pembiakan; selepas pendebungaan, bunga menjadi buah yang mengandungi biji benih."},
    {"topic": "Tumbuhan", "skill": "APPLICATION", "diff": 2,
     "q": "Jika anda meletakkan pokok kecil di tempat gelap selama seminggu, apakah yang berlaku?",
     "opts": ["Daun menjadi lebih hijau", "Daun menjadi kuning", "Tumbuhan membesar cepat", "Tumbuhan berbuah"], "ans": "B",
     "expl": "Tanpa cahaya, fotosintesis berkurangan dan klorofil hilang, menyebabkan daun menjadi kuning (etiolasi)."},
    # --- Haiwan (4) — easy 2, medium 1, hard 1
    {"topic": "Haiwan", "skill": "RECOGNITION", "diff": 1,
     "q": "Haiwan yang hidup di air ialah ...",
     "opts": ["Kucing", "Ikan", "Ayam", "Arnab"], "ans": "B",
     "expl": "Ikan hidup di air (akuatik); kucing, ayam, dan arnab hidup di darat."},
    {"topic": "Haiwan", "skill": "RECOGNITION", "diff": 1,
     "q": "Haiwan yang bertelur dipanggil haiwan ...",
     "opts": ["vivipar", "ovipar", "ovovivipar", "herbivor"], "ans": "B",
     "expl": "Haiwan yang bertelur (contoh: ayam, itik, ikan) dikenali sebagai haiwan ovipar."},
    {"topic": "Haiwan", "skill": "COMPREHENSION", "diff": 2,
     "q": "Apakah persamaan antara kucing dan arnab?",
     "opts": ["Kedua-duanya bertelur", "Kedua-duanya vivipar dan berbulu", "Kedua-duanya hidup di air", "Kedua-duanya berkaki enam"], "ans": "B",
     "expl": "Kucing dan arnab kedua-duanya vivipar (melahirkan anak) dan berbulu — ciri mamalia."},
    {"topic": "Haiwan", "skill": "APPLICATION", "diff": 3,
     "q": "Apakah yang berlaku pada rantai makanan jika semua arnab dibunuh?",
     "opts": ["Rumput tumbuh subur", "Harimau kurang makanan", "Arnab tidak pupus", "Tiada perubahan"], "ans": "B",
     "expl": "Arnab ialah sumber makanan pemangsa. Jika semua arnab mati, pemangsa (contoh: harimau) kehilangan sumber makanan."},
    # --- Manusia (Tubuh, Kesihatan) (4) — easy 3, medium 1
    {"topic": "Manusia", "skill": "RECOGNITION", "diff": 1,
     "q": "Organ yang digunakan untuk bernafas ialah ...",
     "opts": ["Hati", "Paru-paru", "Perut", "Usus"], "ans": "B",
     "expl": "Paru-paru ialah organ pernafasan manusia; hati, perut, dan usus menjalankan fungsi lain."},
    {"topic": "Manusia", "skill": "RECOGNITION", "diff": 1,
     "q": "Alat deria untuk melihat ialah ...",
     "opts": ["Hidung", "Telinga", "Mata", "Lidah"], "ans": "C",
     "expl": "Mata ialah alat deria untuk melihat; hidung (bau), telinga (bunyi), lidah (rasa) untuk deria lain."},
    {"topic": "Manusia", "skill": "APPLICATION", "diff": 1,
     "q": "Apakah yang harus anda lakukan selepas bersukan supaya kekal sihat?",
     "opts": ["Minum air kosong", "Minum air dan rehat", "Terus bersukan tanpa rehat", "Tidur sepanjang hari"], "ans": "B",
     "expl": "Selepas bersukan, badan kehilangan air melalui peluh. Minum air dan rehat membantu pemulihan."},
    {"topic": "Manusia", "skill": "COMPREHENSION", "diff": 2,
     "q": "Mengapa kita perlu makan makanan yang seimbang?",
     "opts": ["Supaya badan mendapat semua nutrien", "Supaya cepat lapar", "Supaya tidak makan", "Tiada sebab"], "ans": "A",
     "expl": "Makanan seimbang membekalkan karbohidrat, protein, vitamin, dan mineral untuk tubuh berfungsi optimum."},
    # --- Benda Bukan Hidup (Ciri) (3) — easy 2, medium 1
    {"topic": "Benda Bukan Hidup", "skill": "RECOGNITION", "diff": 1,
     "q": "Antara berikut, yang manakah benda bukan hidup?",
     "opts": ["Pokok", "Ikan", "Batu", "Burung"], "ans": "C",
     "expl": "Batu tidak bernafas, tidak makan, tidak membesar — ciri benda bukan hidup."},
    {"topic": "Benda Bukan Hidup", "skill": "COMPREHENSION", "diff": 1,
     "q": "Apakah persamaan antara batu dan pensel?",
     "opts": ["Sama-sama bernafas", "Sama-sama benda bukan hidup", "Sama-sama boleh membesar", "Sama-sama hidup"], "ans": "B",
     "expl": "Batu dan pensel kedua-duanya tidak bernafas, makan, atau membesar — benda bukan hidup."},
    {"topic": "Benda Bukan Hidup", "skill": "APPLICATION", "diff": 3,
     "q": "Bola getah dan bola tenis adalah ...",
     "opts": ["Benda hidup", "Benda bukan hidup", "Tumbuhan", "Haiwan"], "ans": "B",
     "expl": "Kedua-dua bola ialah objek buatan manusia — dikategorikan sebagai benda bukan hidup."},
    # --- Bahan (3) — easy 1, medium 2
    {"topic": "Bahan", "skill": "RECOGNITION", "diff": 1,
     "q": "Bahan yang biasa digunakan untuk membuat buku ialah ...",
     "opts": ["Kayu", "Kertas", "Plastik", "Logam"], "ans": "B",
     "expl": "Buku biasanya dibuat daripada kertas (muka surat) dan kadbod (kulit buku)."},
    {"topic": "Bahan", "skill": "RECOGNITION", "diff": 2,
     "q": "Antara berikut, yang manakah bersifat lembut dan mudah dilipat?",
     "opts": ["Batu", "Kaca", "Kertas", "Logam"], "ans": "C",
     "expl": "Kertas ialah bahan lembut dan mudah dilipat, berbeza dengan batu, kaca, dan logam yang keras."},
    {"topic": "Bahan", "skill": "APPLICATION", "diff": 3,
     "q": "Botol minuman biasanya dibuat daripada bahan ...",
     "opts": ["Kaca atau plastik", "Kayu", "Kertas", "Kain"], "ans": "A",
     "expl": "Botol minuman moden dibuat daripada kaca (boleh dikitar semula) atau plastik (ringan dan tahan lama)."},
    # --- Cuaca & Musim (2) — easy 1, medium 1
    {"topic": "Cuaca & Musim", "skill": "RECOGNITION", "diff": 1,
     "q": "Apakah jenis cuaca yang berlaku ketika langit mendung dan hujan turun?",
     "opts": ["Cerah", "Hujan", "Panas", "Berangin"], "ans": "B",
     "expl": "Langit mendung biasanya menghasilkan hujan."},
    {"topic": "Cuaca & Musim", "skill": "COMPREHENSION", "diff": 2,
     "q": "Mengapa kita minum lebih banyak air semasa cuaca panas?",
     "opts": ["Supaya badan lapar", "Supaya badan kekal terhidrat", "Supaya tidak berpeluh", "Supaya cepat letih"], "ans": "B",
     "expl": "Cuaca panas menyebabkan badan kehilangan air melalui peluh. Kita minum lebih banyak air supaya badan kekal terhidrat."},
    # --- Magnet (2) — easy 2
    {"topic": "Magnet", "skill": "RECOGNITION", "diff": 1,
     "q": "Benda manakah yang boleh ditarik oleh magnet?",
     "opts": ["Kertas", "Paku besi", "Kain", "Getah"], "ans": "B",
     "expl": "Magnet menarik bahan feromagnetik seperti besi; kertas, kain, dan getah tidak tertarik."},
    {"topic": "Magnet", "skill": "APPLICATION", "diff": 2,
     "q": "Jika anda kehilangan jarum logam kecil di atas lantai berkarpet, alat apakah yang membantu mencarinya?",
     "opts": ["Sapu", "Magnet", "Buku", "Pensel"], "ans": "B",
     "expl": "Magnet boleh menarik jarum logam (besi); sapu, buku, pensel tidak berkesan untuk logam kecil di karpet."},
]

# =====================================================================
# BAHASA INGGERIS — 20 Q
# Difficulty: easy 12, medium 6, hard 2
# =====================================================================
BI_QUESTIONS = [
    # --- Listening & Speaking (4) — easy 3, medium 1
    {"topic": "Listening & Speaking", "skill": "RECOGNITION", "diff": 1,
     "q": "Your teacher says 'Good morning, class.' What do you say?",
     "opts": ["Good night", "Good morning, teacher", "See you later", "How are you"], "ans": "B",
     "expl": "When greeted with 'Good morning', you reply with 'Good morning' — same greeting."},
    {"topic": "Listening & Speaking", "skill": "RECOGNITION", "diff": 1,
     "q": "Your friend says 'Thank you.' What is a polite reply?",
     "opts": ["You are welcome", "Goodbye", "Sorry", "Please"], "ans": "A",
     "expl": "'You are welcome' is the polite response to 'Thank you'."},
    {"topic": "Listening & Speaking", "skill": "RECOGNITION", "diff": 1,
     "q": "What do you say when you meet someone for the first time?",
     "opts": ["Goodbye", "Nice to meet you", "See you", "Good night"], "ans": "B",
     "expl": "'Nice to meet you' is the polite greeting when meeting someone for the first time."},
    {"topic": "Listening & Speaking", "skill": "COMPREHENSION", "diff": 2,
     "q": "Your teacher says 'Open your book to page 5.' What do you do?",
     "opts": ["Close your book", "Turn to page 5", "Write on the board", "Stand up"], "ans": "B",
     "expl": "'Open your book to page 5' means to turn to page number 5 in your book."},
    # --- Reading (6) — easy 3, medium 2, hard 1
    {"topic": "Reading", "skill": "RECOGNITION", "diff": 1,
     "q": "Which word starts with the letter 'C'?",
     "opts": ["Apple", "Banana", "Cat", "Dog"], "ans": "C",
     "expl": "'Cat' starts with the letter C."},
    {"topic": "Reading", "skill": "RECOGNITION", "diff": 1,
     "q": "Which word is the longest?",
     "opts": ["Cat", "Elephant", "Dog", "Fish"], "ans": "B",
     "expl": "'Elephant' has 8 letters, longer than Cat (3), Dog (3), or Fish (4)."},
    {"topic": "Reading", "skill": "RECOGNITION", "diff": 1,
     "q": "What letter does 'Sun' start with?",
     "opts": ["S", "U", "N", "M"], "ans": "A",
     "expl": "'Sun' starts with the letter S."},
    {"topic": "Reading", "skill": "RECOGNITION", "diff": 2,
     "q": "How many syllables does 'beautiful' have?",
     "opts": ["2", "3", "4", "5"], "ans": "B",
     "expl": "'Beautiful' has 3 syllables: 'beau-ti-ful'."},
    {"topic": "Reading", "skill": "COMPREHENSION", "diff": 2,
     "q": "Read: 'The cat sits on the mat.' Where does the cat sit?",
     "opts": ["On the table", "On the mat", "On the chair", "On the bed"], "ans": "B",
     "expl": "The sentence states 'on the mat' — the cat sits on the mat."},
    {"topic": "Reading", "skill": "COMPREHENSION", "diff": 3,
     "q": "Read: 'Aiman reads a book every night before bed.' What is Aiman doing?",
     "opts": ["Sleeping", "Reading", "Eating", "Playing"], "ans": "B",
     "expl": "'Aiman reads a book' — he is engaged in reading, not sleeping/eating/playing."},
    # --- Writing (5) — easy 3, medium 2
    {"topic": "Writing", "skill": "APPLICATION", "diff": 1,
     "q": "Which is the correct way to write the word at the start of a sentence?",
     "opts": ["kat", "Cat", "cat", "cAt"], "ans": "B",
     "expl": "Capital 'C' is used at the start of a sentence or proper noun; 'Cat' is correct."},
    {"topic": "Writing", "skill": "APPLICATION", "diff": 1,
     "q": "What goes at the end of a declarative sentence?",
     "opts": ["A comma (,)", "A period (.)", "A question mark (?)", "No punctuation"], "ans": "B",
     "expl": "Declarative sentences (statements) end with a period."},
    {"topic": "Writing", "skill": "APPLICATION", "diff": 1,
     "q": "Which sentence uses correct capitalization?",
     "opts": ["mira lives in kl", "Mira Lives in KL", "mira Lives in kl", "Mira lives in kl"], "ans": "B",
     "expl": "'Mira' (proper noun) and 'KL' (abbreviation) should be capitalized at the start."},
    {"topic": "Writing", "skill": "APPLICATION", "diff": 2,
     "q": "Arrange the words to make a correct sentence: 'cat / the / drinks / milk'.",
     "opts": ["The cat drinks milk", "Cat the milk drinks", "Milk drinks the cat", "Drinks cat milk the"], "ans": "A",
     "expl": "Subject + verb + object: 'The cat drinks milk' is grammatically correct."},
    {"topic": "Writing", "skill": "APPLICATION", "diff": 2,
     "q": "What punctuation mark ends a question?",
     "opts": ["Period (.)", "Question mark (?)", "Exclamation mark (!)", "Comma (,)"], "ans": "B",
     "expl": "Questions end with a question mark (?)."},
    # --- Grammar (3) — easy 1, medium 2
    {"topic": "Grammar", "skill": "APPLICATION", "diff": 1,
     "q": "What is the plural of 'cat'?",
     "opts": ["cats", "cat", "cates", "caties"], "ans": "A",
     "expl": "Most nouns form their plural by adding 's': 'cat' becomes 'cats'."},
    {"topic": "Grammar", "skill": "APPLICATION", "diff": 2,
     "q": "Choose the correct sentence:",
     "opts": ["She go to school.", "She goes to school.", "She going to school.", "She gone to school."], "ans": "B",
     "expl": "Third-person singular present tense uses verb + 's': 'go' becomes 'goes'."},
    {"topic": "Grammar", "skill": "APPLICATION", "diff": 2,
     "q": "Which word is an article?",
     "opts": ["Run", "The", "Quickly", "Beautiful"], "ans": "B",
     "expl": "'The' is a definite article; 'a' and 'an' are indefinite articles."},
    # --- Vocabulary (2) — easy 2
    {"topic": "Vocabulary", "skill": "RECOGNITION", "diff": 1,
     "q": "What colour is the sky on a clear day?",
     "opts": ["Green", "Blue", "Red", "Yellow"], "ans": "B",
     "expl": "The sky appears blue on a clear day due to scattering of sunlight."},
    {"topic": "Vocabulary", "skill": "RECOGNITION", "diff": 1,
     "q": "Which animal says 'moo'?",
     "opts": ["Dog", "Cat", "Cow", "Fish"], "ans": "C",
     "expl": "Cows say 'moo' — onomatopoeia for the cow's sound."},
]

# Sanity print
if __name__ == "__main__":
    from collections import Counter
    all_q = []
    for r in BM_QUESTIONS: all_q.append(("BM", r))
    for r in MATH_QUESTIONS: all_q.append(("MATH", r))
    for r in SCI_QUESTIONS: all_q.append(("SCI", r))
    for r in BI_QUESTIONS: all_q.append(("BI", r))
    print(f"BM={len(BM_QUESTIONS)} MATH={len(MATH_QUESTIONS)} SCI={len(SCI_QUESTIONS)} BI={len(BI_QUESTIONS)} TOTAL={len(all_q)}")
    diff = Counter(r["diff"] for sub, r in all_q)
    print(f"Difficulty: easy={diff.get(1,0)} medium={diff.get(2,0)} hard={diff.get(3,0)}")
